language: node_js
node_js:
  - "4"
  - "5"

notifications:
  slack: openframeproject:wGLUMLh5CTAIOGsPUSU8eMf3

install:
  npm install coveralls@^2.11.9 eslint@^2.8.0 istanbul@^0.4.2 mocha@^2.3.4 sinon@^1.17.2 openframe-extension@^0.1.0 debug@^2.2.0

script:
  - npm run test-coveralls